### PR TITLE
Issue 31

### PR DESCRIPTION
**Pull request by lumip**
Large changes to TablePulseTemplates, ParameterDeclarations and Parameters. Covers issue #31 and includes bugfixes. Refer to the commit messages for more details on the changes.

This does not conclude the work on TablePulseTemplates. 
The very least that still has to be done:
- Derived parameters, that depend on others. Some kind of mapping (cf. issue #44).
- Exhaustive tests (cf. issue #30)

### CODE REVIEW

**Comment by pbethke** [comment]
We definitely need tests for the TablePulseTemplate class (maybe building on the example?). Im trying to build a simple pulse and there are undefined variables and logic flaws all over the place. I'm working on it though.

**Comment by lumip** [comment]
The tests will be the next thing I'll cover. I cannot ensure that there are no mistakes if no compiler yells at me when I code. However, given that these changes had to be made, I thought it would be pointless to write the tests first (although that issue was older), then make the changes and have to adapt all the tests..

**Comment by pbethke** [comment]
I am overhauling TablePulseTemplate right now (in the dev branch, if you want to have a look) and am able to resolve a lot of the problems. For now we maybe dont need full unit testing, but just a simple example that should run.

**Comment by lumip** [comment]
Fine. I will look at the changes when you're done, to see the mistakes I've made.
A working example is good, but I will nevertheless create a unit test to ensure that we find as much bugs as possible as soon as I have the time.

**Pull request merged**
