### PR TITLE
Issue 49

### PR DESCRIPTION
**Pull request by pbethke**
Configured a Sphinx documentation stub. There is no actual documentation yet apart from what can be extracted from the docstrings.

### CODE REVIEW

**Comment by lumip** [comment]
I get an error if I call "make dirhtml" (or "make singlehtml", "make doctest", ...) in the doc directory running Windows 7 64b. I've installed sphinx using pip and python 3.5. The error I get is the following:
```
Traceback (most recent call last):
  File "C:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python35\Scripts\sphinx-build.exe\__main__.py", line 9, in <module>
  File "C:\Python35\lib\site-packages\sphinx\__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "C:\Python35\lib\site-packages\sphinx\__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "C:\Python35\lib\site-packages\sphinx\cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "C:\Python35\lib\site-packages\sphinx\application.py", line 37, in <module>
    from sphinx.builders import BUILTIN_BUILDERS
  File "C:\Python35\lib\site-packages\sphinx\builders\__init__.py", line 23, in <module>
    from sphinx.util import i18n, path_stabilize
  File "C:\Python35\lib\site-packages\sphinx\util\i18n.py", line 15, in <module>
    from babel.messages.pofile import read_po
  File "C:\Python35\lib\site-packages\babel\messages\__init__.py", line 12, in <module>
    from babel.messages.catalog import *
  File "C:\Python35\lib\site-packages\babel\messages\catalog.py", line 23, in <module>
    from babel.dates import format_datetime
  File "C:\Python35\lib\site-packages\babel\dates.py", line 28, in <module>
    from babel.util import UTC, LOCALTZ
  File "C:\Python35\lib\site-packages\babel\util.py", line 278, in <module>
    from babel import localtime
  File "C:\Python35\lib\site-packages\babel\localtime\__init__.py", line 21, in <module>
    from babel.localtime._win32 import _get_localzone
  File "C:\Python35\lib\site-packages\babel\localtime\_win32.py", line 18, in <module>
    tz_names = get_global('windows_zone_mapping')
  File "C:\Python35\lib\site-packages\babel\core.py", line 58, in get_global
    _global_data = pickle.load(fileobj)
TypeError: an integer is required (got type str)
```
Do you have any idea how I can fix this before we merge?

**Comment by pbethke** [comment]
Not yet, I'll have a look when I have time, but it's not priority. Let's leave this open until we resolve the issues.

**Comment by lumip** [comment]
It seems that babel v2.0, which is installed alongside sphinx, causes this bug for Windows. [This spinx issue](https://github.com/sphinx-doc/sphinx/issues/1976) suggests reverting back to babel v1.3, which works for me.
However, the generated documentation contains some dead links, i.e. pages that are linked do not exist, which I find somewhat irritating. We should look into that.

**Comment by pbethke** [comment]
I am aware of the missing pages issue. This is just a stub for sphinx


---- Lukas Prediger schrieb ----


It seems that babel v2.0, which is installed alongside sphinx, causes this bug for Windows. This spinx issue<https://github.com/sphinx-doc/sphinx/issues/1976> suggests reverting back to babel v1.3, which works for me.
However, the generated documentation contains some dead links, i.e. pages that are linked do not exist, which I find somewhat irritating. We should look into that.

**Pull request merged**
