### PR TITLE
Make the trivial changes to Google style docstrings

### PR DESCRIPTION
**Pull request by pbethke**
Relates to #53.

### CODE REVIEW

**Comment by lumip** [comment]
This seems fine. However, in the docstring of the ParameterDeclaration constructor, the information that the arguments are keyword arguments are lost. The example referenced in #53 states that
"If \*args or \*\*kwargs are accepted,
    they should be listed as ``*args`` and ``**kwargs`` [in the 'Args:' section]."

**Comment by pbethke** [comment]
Why do you use **kwargs anyway instead of naming them?

This whole block is a bit weird:
```python
def __init__(self, **kwargs) -> None:
    # Docstring
    super().__init__()
    self._min_value = None
    self._max_value = None
    self._default_value = None
    for key in kwargs:
        value = kwargs[key]
        if isinstance(value, numbers.Real):
            if key == "min":
                self._min_value = value
            elif key == "max":
                self._max_value = value
            elif key == "default":
                self._default_value = value
        else:
            raise ValueError("{0} is not a valid argument.".format(key))
        else:
            ... # Assertions
```

the only values in **kwargs that are ever going to matter are ```min, max, default```. You check if they are present and replace them by their default value otherwise. Why not just use

```python
def __init__(self, min=None, max=None, default=None) -> None:
    # Assertions, make sure it's a real number, etc.
```
instead?

**Comment by lumip** [comment]
The reasoning behind this was that the parameters are all optional. Maybe a user only wants to specify a default value but not min and max. It is then more convenient and descriptive (in my opinion) to just type `ParameterDeclaration(default=0.4)` instead of `ParameterDeclaration(None, None, 0.4)`. 
After all, such a simplification for the user is the essential benefit I see in keyword arguments.

**Comment by pbethke** [comment]
keyword parameters in Python are always optional and unordered, so ```ParameterDeclaration(default=4.0)``` is perfectly fine.

**Comment by lumip** [comment]
Ah, I see. I'll adapt the parameter list to follow your suggestion.

**Pull request merged**
